---
title: "Untitled"
author: "Masumbuko Semba"
date: "November 19, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("E:/Data Manipulation/mafia_kilwa_octopus_mapping/CFMA shapefiles/")
```

```{r}
files = dir(path =  "E:/Data Manipulation/mafia_kilwa_octopus_mapping/CFMA shapefiles/", pattern = ".shp", include.dirs = TRUE, full.names = TRUE)
```

```{r}
require(sf)
require(tidyverse)
```

```{r}

# for (i in 1:length(files)){
  
  
 wwf = st_read(files[15])

ggplot() + 
  geom_sf(data = wwf, fill = "red", col =1, alpha = 0.25)
# }

```


## Data Sources, Processing and Analysis
```{r packages, comment="", message=FALSE, warning=FALSE}

# load Packages we need for data manipulation and analysis
require(sf)
require(ncdf4)
# require(R.matlab)
require(pracma)
# require(cowplot)
require(tidyverse)
require(ggsn)
require(insol)
# require(RColorBrewer)
require(lubridate)
require(forecast)
# require(ggpubr)
require(akima)
require(fields)
require(maptools)
require(marmap)
require(oce)
require(ggsci)
# require(mapview)
# require(mapedit)
require(tmap)

# # clear the worksapce
# clear()

```

```{r include=FALSE, warning=FALSE}
##read Africa continental shapefile that we will use throught the munuscript as basemap dataset for maps
africa = read_sf("E:/GIS/Tanzania spatial data Bank/EAF14 Tanzania spatial datasets/africa/Spatial/AdmInfr/afcntry.shp")

## clean the file
tz.ke = africa%>%select(-c(FIPS_CNTRY, REGIONA, EMPTY, EMPTY2))%>%
  filter(CNTRY_NAME == "Tanzania" | CNTRY_NAME == "Kenya")
```


```{r}
# read etopo 1 ascii file
etopo = read.asciigrid("E:/GIS/ROADMAP/Etopo 1/Tanzania_etopo1/tanz1_-3432.asc")
# convert the etopo file into tibble
etopo.df = as.data.frame(etopo)%>%as.tibble()

# tidy the data
etopo.df = etopo.df%>%
  rename(lon = s1,lat = s2, bathmetry = E..GIS.ROADMAP.Etopo.1.Tanzania_etopo1.tanz1_.3432.asc)%>%
  select(lon,lat, bathmetry)

# select the bathmetry value only within the pemba channel area of interest
bathmetry = etopo.df%>%filter(lon>=39 & lon <=41 & lat >=-11 & lat <= -7 & bathmetry <=0)

```


```{r}
ggplot() + 
  geom_raster(data = bathmetry %>% filter(bathmetry > -40 & bathmetry <5), 
              aes(x = lon, y = lat, fill = bathmetry), interpolate = TRUE)+
  geom_sf(data = tz.ke, fill = "grey70", col = 1)+
  coord_sf(ylim = c(-8.3,-7.5), xlim = c(39.25,39.9))+
  geom_contour(data = bathmetry %>% filter(bathmetry > -40 & bathmetry <5), 
              aes(x = lon, y = lat, z = bathmetry), breaks = seq(-40, 0, 4), col = "grey50")+
  geom_contour(data = bathmetry %>% filter(bathmetry > -40 & bathmetry <5), 
              aes(x = lon, y = lat, z = bathmetry), breaks = seq(-40, 0, 5), col = 1)+
  theme_bw()+
  theme(panel.background = element_rect(colour = 1, fill = "grey90"),
        panel.grid = element_line(colour = "grey70"),
        legend.direction = "horizontal",
        legend.position = c(.85,.06),
        legend.background = element_rect(colour = 1, fill = "grey85"),
        axis.text = element_text(size = 10, colour = "grey30"))+
  scale_fill_gradientn(colours = oceColorsGebco(120), name = "", 
                       breaks = seq(-35,-5,10),
                       label = seq(35,5,-10))+
  scale_x_continuous(breaks = seq(39.3,40, length.out = 5) %>% round(digits = 2))+
  labs(x = NULL, y = NULL)
  
```



```{r}
ggplot()+
   geom_contour(data = bathmetry%>%filter(depth>=5 & depth >=-100),
               aes(x = lon, y = lat, z= bathmetry),
               breaks =seq(-1000,-1,5), col = "grey70", lwd = .4)+
  geom_contour(data = etopo.tb%>%filter(depth<=20 & depth >=-1000), 
               aes(x = lon, y = lat, z= depth), 
               breaks =seq(-1000,-1,100), col = 1, lwd = .5)+
  geom_sf(data = africa, fill = "grey80", col = 1)+
  coord_sf(xlim = c(39,39.8), ylim = c(-5.6,-4))+
  # coord_sf(xlim = c(38.95,39.8), ylim = c(-5.6,-4.8))+
  # scale_x_continuous(breaks = c(39,39.7))+
  # scale_y_continuous(breaks = c(-5.5, -4.9))+
  theme_bw(base_size = 12)+
  theme(panel.background = element_rect(fill = "white", colour = 1, size = 1.2),
        axis.text = element_text(colour = 1, size = 11))+
  labs(x = "", y = "")+
  scalebar(location = "bottomright", y.min = -5.6, y.max = -4.7, 
           x.min = 39.0, x.max = 39.8, dist = 15, dd2km = TRUE, 
           model = "WGS84", st.dist = 0.02, st.size = 4)
```




```{r fig2, fig.cap="The bathymetry of the Pemba channel. The black isobars are hundred meters intervals and gray isobars are twenty meters interval. The inset plot shows the bottom topography of the Pemba channel along the dotted red line. "}


# pemba.transect.depth = read_csv("pemba_transect_depth.csv")%>%filter(depth <= 0)
# 
# Lon = seq(min(pemba.transect.depth$lon),
#           max(pemba.transect.depth$lon),
#           length.out = 100)
# 
# Lat = seq(min(pemba.transect.depth$lat),
#           max(pemba.transect.depth$lat),
#           length.out = 100)
# 
# Depth = interp1(x =  pemba.transect.depth$lon,
#                        y =  pemba.transect.depth$depth, 
#                        xi = Lon,
#                        method = "spline")



pemba.transect.depth.interp = data_frame(Lon,Lat, Depth)

pemba.transect.depth.interp = pemba.transect.depth.interp%>%
  mutate(dist = geodDist(pemba.transect.depth.interp$Lon,
                         pemba.transect.depth.interp$Lat, 
                         alongPath = T))


#map the bathmetry with ggplot2
bath.map = ggplot()+
   geom_contour(data = etopo.tb%>%filter(depth<=20 & depth >=-1000), 
               aes(x = lon, y = lat, z= depth), 
               breaks =seq(-1000,-1,20), col = "grey70", lwd = .4)+
  geom_contour(data = etopo.tb%>%filter(depth<=20 & depth >=-1000), 
               aes(x = lon, y = lat, z= depth), 
               breaks =seq(-1000,-1,100), col = 1, lwd = .5)+
  geom_sf(data = africa, fill = "grey80", col = 1)+
  geom_path(data = pemba.transect.depth, 
            aes(x = lon, y = lat),  col = 2, lwd = 1.5, linetype = 2)+
  coord_sf(xlim = c(39,39.8), ylim = c(-5.6,-4))+
  # coord_sf(xlim = c(38.95,39.8), ylim = c(-5.6,-4.8))+
  # scale_x_continuous(breaks = c(39,39.7))+
  # scale_y_continuous(breaks = c(-5.5, -4.9))+
  theme_bw(base_size = 12)+
  theme(panel.background = element_rect(fill = "white", colour = 1, size = 1.2),
        axis.text = element_text(colour = 1, size = 11))+
  labs(x = "", y = "")+
  scalebar(location = "bottomright", y.min = -5.6, y.max = -4.7, 
           x.min = 39.0, x.max = 39.8, dist = 15, dd2km = TRUE, 
           model = "WGS84", st.dist = 0.02, st.size = 4)


depth.profile = ggplot(data = pemba.transect.depth.interp, 
                       aes(x = dist, y = abs(Depth)))+
  geom_path(size = 1, col = 2)+
  scale_x_continuous(breaks = seq(0,80,20))+
  scale_y_reverse(breaks = seq(0,1000,200))+
  xlab("Distance (km)")+
  ylab("Depth (m)")+
  theme_bw(base_size = 12)+
  theme(panel.background = element_rect(fill = "white", colour = 1, size = 1),
        plot.background = element_rect(fill = NA, colour = NA),
        axis.text = element_text(colour = 1),
        panel.grid = element_line(colour = NA))

# inset the depth profile figure on the map of bath
cowplot::ggdraw()+
  cowplot::draw_plot(bath.map, 0,0,1,1)+
  cowplot::draw_plot(depth.profile, 0.31,0.68,.3,.3)

# ggsave("Fig 2.png", dpi = 600)


```

